### ISSUE TITLE
Train Station Scaling Changes Player Collision

### ISSUE THREAD

**Issue by Pengegg** [Moondrixx/AcrylicaGame#8]
Due to the scaling of the station prefab the player's collision capsule is scaled due to parent-child property inheritance.

To Recreate:

- Spawn a player prefab

- Take note of the size of player's collision capsule

- Spawn the station prefab that includes the player

- Note how the player's collision capsule looks very tall and skinny

Likely fixed by not scaling the train model's transform, but rather the fbx during import

**Comment by Moondrixx** [comment]
fixed, a reminder to everyone that when adding new assets, to scale them to fit what's already in the scene not the other way around
